### ISSUE TITLE
Use React-skeletor for loading screens

### ISSUE THREAD

**Issue by wildlifehexagon** [dictyBase/Genomepage#1]
This will be used instead of a spinner for loading screens.

https://codeburst.io/achieve-skeleton-loading-with-react-a12404678030
https://github.com/trainline/react-skeletor

**Comment by cybersiddhu** [comment]
I think it will be preferable to know the css technique to build up the screens. 
https://codepen.io/oslego/pen/XdvWmd/
https://css-tricks.com/building-skeleton-screens-css-custom-properties/
And maybe used them directly and compare to decide if it's worth using the module.

**Comment by wildlifehexagon** [comment]
Tried this out on DSC and it worked great: https://github.com/dvtng/react-loading-skeleton
