### ISSUE TITLE
New column structure for GO tab

### ISSUE THREAD

**Issue by wildlifehexagon** [dictyBase/Genomepage#29]
New suggestion:

_qualifier_ term | evidence | with | _relation_ extension | reference | Date 

Example of annotation:

Gene Information for abcA

- _enables_ protein phosphorylation | IDA |   | _happens during_ sorocarp stalk cell differentiation | PMID:1234567 | 2018-05-18
- _enables_ protein binding | IDA | abcB |     | PMID:1234567 | 2018-05-18
- _involved in_ protein localization to centrosome | IMP | _has input_ sun1  | PMID:1234567 | 2018-05-18

**Comment by pfey03** [comment]
Note that any annotation can also have >1 extension. For example

involved in protein localization to centrosome | IMP | has input sun1, _happens during_ chemotaxis to cAMP | PMID:1234567 | 2018-05-18

Note also, in Protein2GO >1 extensions are either separated by Pipe or Comma:
| signifies an independent AND/OR statement
, signifies a CONCURRENT statement

So the above example (not a real annotation) is the latter, extensions separated by a comma.
Should be visible in file. 

Thanks!!
