### ISSUE TITLE
Update GO panel display on summary page

### ISSUE THREAD

**Issue by wildlifehexagon** [dictyBase/Genomepage#36]
Keep the table setup but only display the last five by date for each row. These should be separated by lines rather than commas.

**Comment by wildlifehexagon** [comment]
https://github.com/dictyBase/Migration/issues/111
https://github.com/dictyBase/Migration/issues/110

**Comment by wildlifehexagon** [comment]
Example of gene with multiple extensions, including multiple for one term:

https://betafunc.dictybase.org/genes/DDB_G0280531/goas

**Comment by pfey03** [comment]
here is one with many CHEBI extensions to a process term: DDB_G0272004
the gene with SO extension: DDB_G0278741

**Comment by pfey03** [comment]
maybe also linking the RNA annotation issue here
https://github.com/dictyBase/Migration/issues/109

**Comment by wildlifehexagon** [comment]
The summary display has been updated in version `2.0.0` which will be deployed very soon.
