### ISSUE TITLE
Informative error messages in case of non-existent gene name(or id)

### ISSUE THREAD

**Issue by cybersiddhu** [dictyBase/Genomepage#60]
We get the following error display when you to open https://testdb.dictybase.org/gene/tbc1d5B.
![screenshot-2018-10-25 dictybase genomepage](https://user-images.githubusercontent.com/48740/47503449-c382ec80-d82f-11e8-8faa-7da8cadcb92d.png). Since this is case of non-existent name(or id), it should not fall into the category of server side error. Server side error is for unexpected or unrecoverable situation in the server generally reserved for case when something seriously went wrong with the server.
Instead, under the identical situation, the display of legacy dictybase  provides a informative context to the user. 
![screenshot_2018-10-25 record not found](https://user-images.githubusercontent.com/48740/47503852-ac90ca00-d830-11e8-9c34-a380aa9c15f0.png)
  
https://github.com/dictybase-playground/kubeless-nodefn/issues/10

**Comment by wildlifehexagon** [comment]
This problem was fixed on the backend shortly after the previous post -- the update just needs to be pushed in production.
