### ISSUE TITLE
Refactor the render method

### ISSUE THREAD

**Issue by cybersiddhu** [dictyBase/Genomepage#62]
https://github.com/dictyBase/Genomepage/blob/ee3986f3f9c0993468df623b793310d168d2623d/src/app/layout/App.js#L68

* Reduce multi argument checks in the `if` block. You could convert `!navbar.links` and `!footer.links` into error, so at least it will become `if (navbar.error || footer.error)` 
* Now the issue with above logic is you're not covering for `if (navbar.error && footer.error)`. Now if you do this 
```js
if (navbar.error || footer.error) {
   return 'something'
}
if (navbar.error && footer.error)  {
   return 'something'
}
```
in any sequence, it might leave out one of the error checking, because `navbar.error || footer.error` will never go to `footer.error` is `navbar.error` is true. You could use a boolean along with two if blocks to handle the situation.
```js
let navOrFootterError = false
let navbarErrorUI
let footerErrorUI
if (navbar.error) {
   navOrFooterError = true
   navbarErrorUI = '<navbarErrorUIComponent />'
}
if (footer.error) { 
   navOrFooterError = true
   footerErrorUI = '<footerErrorUIComponent />'
}
if (navOrFooterError) { 
   return <Something>{navbarErrorUI}{footerErrorUI}</Something>
}
```

**Comment by cybersiddhu** [comment]
### Approach to refactoring
* Instead of  sequential `fetchNavbar()` and `fetchFooter()` methods in the lifecycle, combine them to one action call. In the action call do the sequential fetches. 
* Refactor the reusable pieces into a `HOC` or `render prop` component. The reusable pieces will be
  - Fetching the data.
  - Handling errors. 
  - In case of successful fetch, hand over the data to the child component that is wrapped by the `HOC` or `render prop`

**Comment by wildlifehexagon** [comment]
I have refactored the `render` method as specified in the above comment. However, after adding my `withDataFetching` HOC to the `App` component, the `SummaryContainer` component is now being mounted and rendered three different times. Still trying to determine why this is happening.
