### ISSUE TITLE
Convert all gene IDs to names

### ISSUE THREAD

**Issue by wildlifehexagon** [dictyBase/Genomepage#66]
Example: https://testdb.dictybase.org/gene/gskA/goannotations

Make sure Uniprot ID -> gene ID goes to name if applicable.

Also update the links to go to gene page, not uniprot.

**Comment by wildlifehexagon** [comment]
All names are properly being converted on the frontend now, and I wrote unit tests with 100% coverage to verify this. This will be live in the next release.

The backend has also been patched, and once that goes live this issue and #68 will be fixed.

**Comment by erichartline** [comment]
Fixed in `3.2.0`
