### ISSUE TITLE
Duplicate lines on GO tab

### ISSUE THREAD

**Issue by wildlifehexagon** [dictyBase/Genomepage#68]
Any lines that contain extensions are showing up twice on the GO page.

See here for example: https://testdb.dictybase.org/gene/gskA/goannotations

**Comment by pfey03** [comment]
Oh yes, saw that and since there were so many issues forgot. This is a bad one and would be nice to fix before I give the talk and i want to make slides in case internet is shaky. So this is urgent,

Thanks!

**Comment by wildlifehexagon** [comment]
This was an issue with the `kubeless-nodefn` backend. When I added the `With` conversions, I included one extra `push` into my array. I have cleaned those up and the script is working as expected locally. Will double-check it in the morning before releasing properly.

**Comment by erichartline** [comment]
Fixed in `3.2.0`
