### ISSUE TITLE
arrow on MF and CC GO regulate BP but not their own section

### ISSUE THREAD

**Issue by pfey03** [dictyBase/Genomepage#71]
The little sort arrows for each GO section are messed up. Arrows in any section all change direction of the middle BP section, and MF and CC are not sorted. Looks like a 'copy/paste' issue to me.

Please fix! should be quick. Thanks!

**Comment by wildlifehexagon** [comment]
Bug is only in sorting the first column. Will investigate further.

**Comment by wildlifehexagon** [comment]
After investigating some more, the sorting is actually working for every column, but it's only sorting by the qualifier and not the GO term after. So when you go to a gene page and every qualifier is `enables`, for example, it will only sort by that term. I'm going to look into having it sort by the GO term if all qualifiers are the same.

**Comment by wildlifehexagon** [comment]
Per our discussion, I have changed the default sorting to be by date (new -> old). This will be reflected in the new update.
