### ISSUE TITLE
Dicty anatomy term in extensions looks like link but goes nowhere

### ISSUE THREAD

**Issue by pfey03** [dictyBase/Genomepage#73]
this gene
https://testdb.dictybase.org/gene/DDB_G0287317/goannotations#
has a DDANAT term linked in an extensions. Click and it goes nowhere.

1. Display Anatomy **Term**: This might need a script to display the term and just look it up on our Git page e.g. ID DDANAT:0000405
https://github.com/dictyBase/migration-data/blob/master/ontologies/dicty_anatomy.obo
2. **Link** the term to Ontobee http://www.ontobee.org/ontology/DDANAT?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FDDANAT_0000405

I don't know how many anatomy terms there are but there should be several.

Thanks!

ps, this page also doesn't recognize gene name : splA

**Comment by erichartline** [comment]
Link has been added. Term conversion progress will be updated here: #79
