### ISSUE TITLE
Upgrade Node CI Develop to v14.17.0

### ISSUE THREAD

**Issue by ayaanqui** [dictyBase/Genomepage#817]
Build failures with `node-ci-dev.yml` because it uses node `v14.16.1`. So this pull request tries to find the problem and then upgrade to node `v14.17.0`. See [Node CI Develop build errors](https://github.com/dictyBase/genomepage/runs/4171360839?check_suite_focus=true).
```
#16 0.310 error genomepage@0.0.0-semantically-released: The engine "node" is incompatible with this module. Expected version ">= 14.17". Got "14.16.1"
```

**Comment by JSneak** [comment]
https://github.com/dictyBase/genomepage/blob/develop/.github/workflows/node-ci-dev.yml

Should be fixed already. We have node version 16
