### ISSUE TITLE
Feat: Add phenotypes tab on gene summary page

### ISSUE THREAD

**Issue by ayaanqui** [dictyBase/Genomepage#824]
As discussed with @cybersiddhu there needs to be a tab that lets users browse the phenotypes for a given gene, similar to how the legacy dictyBase website did.

![image](https://user-images.githubusercontent.com/25919063/142295189-1727e3ca-7396-481f-9ee9-fe23684b3abc.png)

The screenshot shown above is taken from [http://dictybase.org/gene/DDB_G0282853/phenotypes](http://dictybase.org/gene/DDB_G0282853/phenotypes). As shown, the website uses a tab that the user can click which will display table with the information. The new website should have a similar feature on the `/gene/:gene` page with a tab to access the phenotypes information for a given gene.

**Comment by cybersiddhu** [comment]
Make sure to decide on a router path, make sure it's not too much nested.

**Comment by ayaanqui** [comment]
Got it, I'll try to keep it simple but also make it somewhat descriptive and show you the mock-ups.
